---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    app.kubernetes.io/name: app1
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app1
    spec:
      containers:
      - name: app1
        image: docker.io/vfarcic/silly-demo:1.1.3
        ports:
          - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  labels:
    app.kubernetes.io/name: app2
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app2
    spec:
      containers:
      - name: app2
        image: docker.io/vfarcic/silly-demo:1.1.3
        ports:
          - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3
  labels:
    app.kubernetes.io/name: app3
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app3
    spec:
      containers:
      - name: app3
        image: docker.io/vfarcic/silly-demo:1.1.3
        ports:
          - containerPort: 8080
