---
apiVersion: v1
kind: Service
metadata:
  name: app1
  labels:
    app.kubernetes.io/name: app1
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: app1
---
apiVersion: v1
kind: Service
metadata:
  name: app2
  labels:
    app.kubernetes.io/name: app2
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: app2
---
apiVersion: v1
kind: Service
metadata:
  name: app3
  labels:
    app.kubernetes.io/name: app3
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: app3
